spring:
  application:
    name: client
server:
  port: 8082
  context-path: /client
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://localhost:8090/eureka/
     
feign:
  hystrix: 
    enabled: true

hystrix: 
  command: 
    default: 
      execution: 
        timeout: 
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 2000
  threadpool: 
    default: 
      coreSize: 10
      maxQueueSize: 8
      queueSizeRejectionThreshold: 8
