
spring:
  application:
    name: gas-station
  datasource:
    name: ikcrm
#    url: jdbc:mysql://localhost:3306/gasstation?characterEncoding=utf8&autoReconnect=true&useSSL=false
    url: jdbc:mysql://localhost:3306/gasstation?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 2
    maxWait: 60000
    minIdle: 8
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 120000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
server:
  port: 8090
  servlet: 
    context-path: /gas

mybatis:
  type-aliases-package: com.heyc.gasstation.softem.entity
  mapper-locations: classpath*:com/heyc/gasstation/softem/dao/*Mapper.xml
  mapper: com.heyc.gasstation.softem.utils.BaseMpper
  not-empty: false
  identity: MYSQL
logging:
  level:
    com:
      heyc:
        gasstation:
          softem: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
